### ISSUE TITLE
Doesn't install on travis.ci; dom version 0.0.0 not found

### ISSUE THREAD

**Issue by evantahler** [defunctzombie/docserv#5]
From travis.ci:

```
silly registry.get cb [ 200,
silly registry.get   { vary: 'Accept',
silly registry.get     server: 'CouchDB/1.2.0 (Erlang OTP/R15B)',
silly registry.get     etag: '"4EZJ2NMVN2NWQ80060QNF54MY"',
silly registry.get     date: 'Wed, 02 Jan 2013 17:07:21 GMT',
silly registry.get     'content-type': 'application/json',
silly registry.get     'content-length': '4272' } ]
error Error: No compatible version found: dom@'shtylman/dom'
error Valid install targets:
error ["0.0.0"]
error     at installTargetsError (/home/travis/.nvm/v0.8.11/lib/node_modules/npm/lib/cache.js:553:10)
error     at /home/travis/.nvm/v0.8.11/lib/node_modules/npm/lib/cache.js:477:15
error     at saved (/home/travis/.nvm/v0.8.11/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
error     at /home/travis/.nvm/v0.8.11/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
error     at Object.oncomplete (fs.js:297:15)
error If you need help, you may report this log at:
error     <http://github.com/isaacs/npm/issues>
error or email it to:
error     <npm-@googlegroups.com>
error System Linux 3.2.0-29-generic-pae
error command "/home/travis/.nvm/v0.8.11/bin/node" "/home/travis/.nvm/v0.8.11/bin/npm" "install"
error cwd /home/travis/builds/evantahler/actionHero
error node -v v0.8.11
error npm -v 1.1.62
verbose exit [ 1, true ]
```

**Comment by defunctzombie** [comment]
The version of node travis is using is too old for the shorthand github style dependency "shtylman/dom".

I just got the 'dom' name on npm so will update the package to use that.

For now I would remove it from your deps :)
